### PR TITLE
BSidesSF 2020 writeups

### PR DESCRIPTION
**Pull request by Pharisaeus**

### CODE REVIEW

**Comment by Pharisaeus** [comment]
@XeR you could have also linked them on ctftime since I can't attribute them to TFNS ;)

**Comment by XeR** [comment]
> @XeR you could have also linked them on ctftime since I can't attribute them to TFNS ;)

Done. I wanted to get agreement before submitting them to CTFtime.
I took the freedom to split `toast` in `toast-clicker1`, `toast-clicker2` and `toast-clicker3` on CTFtime.

Thanks for your hard work !

**Comment by Pharisaeus** [comment]
@XeR I just noticed, you missed mpfrag on ctftime.

**Comment by XeR** [comment]
[Fixed](https://ctftime.org/writeup/18526), sorry

**Pull request merged**
